skip_docs

fastlane_require 'dotenv'

platform :android do
  desc "Create a build"
  lane :build do |options|
    Dotenv.overload '../env/.env'

    file = getFolderPath().concat(ENV['ANDROID_STORE_FILE'])
    version = load_json(json_path: "package.json")["version"]

    android_set_version_name(
      version_name: version,
      gradle_file: "./android/app/build.gradle"
    )

    android_set_version_code(
      version_code: number_of_commits(),
      gradle_file: "android/app/build.gradle"
    )

    gradle(
      task: 'clean assemble bundle',
      build_type: options[:type] || 'release',
      project_dir: 'android/',
      properties: {
        "android.injected.signing.store.file" => file,
        "android.injected.signing.store.password" => ENV['ANDROID_STORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['ANDROID_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['ANDROID_KEY_PASSWORD'],
        "versionName" => version,
      },
      print_command_output: true,
      print_command: true
    )

    puts "APK: #{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    puts "AAB: #{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"
  end

end

lane :getFolderPath do
  sh(
    command: 'cd ../ && pwd',
    log: true
  ).chomp.concat('/')
end
